### ISSUE TITLE
For the explanation of the new algo

### ISSUE THREAD

**Issue by landry0103** [deterrionc/centrabit-trading-scripts#48]
I wrote it in the readme file, the the format is not good, would you please check in your side? 
The markdown format is not good to show. :(
Please review it @deterrionc

**Comment by deterrionc** [comment]
Ok, it would be good, we don't do marketing for now, we are doing it for the understanding of the users.
So I think we can leave it for now. 
I will care of it after the work done. @landry0103

**Comment by landry0103** [comment]
Perfect thank you! @deterrionc
