### ISSUE TITLE
Graph drawing

### ISSUE THREAD

**Issue by deterrionc** [deterrionc/centrabit-trading-scripts#49]
In new algo script, you need to show the limitations of lines in the chart. 
Please add it in the script functionality.
Can you do it? @deterrionc

**Comment by landry0103** [comment]
Yeah!
Thanks for letting me know that. 
I will do it right away. 
For the chart drawing, we can use the built-in libraries. 
We don't need to create new drawing functions.

**Comment by deterrionc** [comment]
ok
